remote_theme: pmarsceill/just-the-docs
title: Quizlet.JS
description: Quizlet.JS Desc
domain: quizlet.js.org
baseurl: /
url: https://quizlet.js.org
permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]
search_enabled: true
search:
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false
heading_anchors: true
aux_links:
  "Quizlet.JS on GitHub":
    - "//github.com/RedYetiDev/Quizlet.JS"
aux_links_new_tab: false
nav_sort: case_sensitive # Capital letters sorted before lowercase
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 RedYetiDev. Distributed by an <a href=\"https://github.com/RedYetiDev/Quizlet.JS/tree/master/LICENSE\">MIT license.</a>"
last_edit_timestamp: false # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
color_scheme: dark

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
## ga_tracking: UA-2709176-10
ga_tracking_anonymize_ip: true

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all