remote_theme: pmarsceill/just-the-docs
theme: just-the-docs
title: Quizlet.JS
description: Quizlet.JS is a node.js client for Quizlet Live
domain: quizlet.js.org
baseurl: /
url: https://quizlet.js.org
permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false
heading_anchors: true
aux_links:
  "Quizlet.JS on GitHub":
    - "//github.com/RedYetiDev/Quizlet.JS"
aux_links_new_tab: false
nav_sort: case_sensitive
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2021 RedYetiDev. Distributed by an <a href=\"https://github.com/RedYetiDev/Quizlet.JS/tree/master/LICENSE\">MIT license.</a>"
last_edit_timestamp: false
plugins:
  - jekyll-seo-tag
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false